export const data = {
  shelly: {
    rarity: "Starting Brawler",
    class: "Damage Dealer",
    gender: "Female", 
    released: "2017",
  },
  colt: {
    rarity: "Rare",
    class: "Damage Dealer",
    gender: "Male",
    released: "2017",
  },
  bull: {
    rarity: "Rare",
    class: "Tank",
    gender: "Male",
    released: "2017",
  },
  brock: {
    rarity: "Rare",
    class: "Marksman",
    gender: "Male", 
    released: "2017",
  },
  rico: {
    rarity: "Super Rare",
    class: "Damage Dealer",
    gender: "Male", 
    released: "2017",
  },
  spike: {
    rarity: "Legendary",
    class: "Damage Dealer",
    gender: "Non-binary",
    released: "2017",
  },
  barley: {
    rarity: "Rare",
    class: "Artillery",
    gender: "Male",
    released: "2017",
  },
  jessie: {
    rarity: "Super Rare",
    class: "Controller",
    gender: "Female",
    released: "2017",
  },
  nita: {
    rarity: "Rare",
    class: "Damage Dealer",
    gender: "Female",
    released: "2017",
  },
  dynamike: {
    rarity: "Super Rare",
    class: "Artillery",
    gender: "Male",
    released: "2017",
  },
  "el primo": {
    rarity: "Rare",
    class: "Tank",
    gender: "Male",
    released: "2017",
  },
  mortis: {
    rarity: "Mythic",
    class: "Assassin",
    gender: "Male",
    released: "2017",
  },
  crow: {
    rarity: "Legendary",
    class: "Assassin",
    gender: "Male",
    released: "2017",
  },
  poco: {
    rarity: "Rare",
    class: "Support",
    gender: "Male",
    released: "2017",
  },
  bo: {
    rarity: "Epic",
    class: "Controller",
    gender: "Male",
    released: "2017",
  },
  piper: {
    rarity: "Epic",
    class: "Marksman",
    gender: "Female", 
    released: "2017",
  },
  pam: {
    rarity: "Epic",
    class: "Support",
    gender: "Female",
    released: "2017",
  },
  tara: {
    rarity: "Mythic",
    class: "Damage Dealer",
    gender: "Female", 
    released: "2017",
  },
  darryl: {
    rarity: "Super Rare",
    class: "Tank",
    gender: "Male", 
    released: "2017",
  },
  penny: {
    rarity: "Super Rare",
    class: "Controller",
    gender: "Female",
    released: "2018",
  },
  frank: {
    rarity: "Epic",
    class: "Tank",
    gender: "Male",
    released: "2018",
  },
  gene: {
    rarity: "Mythic",
    class: "Controller",
    gender: "Male",
    released: "2019",
  },
  tick: {
    rarity: "Super Rare",
    class: "Artillery",
    gender: "Non-binary",
    released: "2019",
  },
  leon: {
    rarity: "Legendary",
    class: "Assassin",
    gender: "Male", 
    released: "2018",
  },
  rosa: {
    rarity: "Rare",
    class: "Tank",
    gender: "Female",
    released: "2019",
  },
  carl: {
    rarity: "Super Rare",
    class: "Damage Dealer",
    gender: "Male",
    released: "2019",
  },
  bibi: {
    rarity: "Epic",
    class: "Tank",
    gender: "Female",
    released: "2019",
  },
  "8-bit": {
    rarity: "Super Rare",
    class: "Damage Dealer",
    gender: "Non-binary",
    released: "2019",
  },
  sandy: {
    rarity: "Legendary",
    class: "Controller",
    gender: "Male",
    released: "2019",
  },
  bea: {
    rarity: "Epic",
    class: "Marksman",
    gender: "Female",
    released: "2019",
  },
  emz: {
    rarity: "Epic",
    class: "Controller",
    gender: "Female",
    released: "2019",
  },
  "mr. p": {
    rarity: "Mythic",
    class: "Controller",
    gender: "Male",
    released: "2020",
  },
  max: {
    rarity: "Mythic",
    class: "Support",
    gender: "Female",
    released: "2019",
  },
  jacky: {
    rarity: "Super Rare",
    class: "Tank",
    gender: "Female",
    released: "2020",
  },
  gale: {
    rarity: "Epic",
    class: "Controller",
    gender: "Male",
    released: "2020",
  },
  nani: {
    rarity: "Epic",
    class: "Marksman",
    gender: "Female",
    released: "2020",
  },
  sprout: {
    rarity: "Mythic",
    class: "Artillery",
    gender: "Non-binary",
    released: "2020",
  },
  surge: {
    rarity: "Legendary",
    class: "Damage Dealer",
    gender: "Male",
    released: "2020",
  },
  colette: {
    rarity: "Epic",
    class: "Damage Dealer",
    gender: "Female",
    released: "2020",
  },
  amber: {
    rarity: "Legendary",
    class: "Controller",
    gender: "Female",
    released: "2020",
  },
  lou: {
    rarity: "Mythic",
    class: "Controller",
    gender: "Male",
    released: "2020",
  },
  byron: {
    rarity: "Mythic",
    class: "Support",
    gender: "Male",
    released: "2020",
  },
  edgar: {
    rarity: "Epic",
    class: "Assassin",
    gender: "Male",
    released: "2020",
  },
  ruffs: {
    rarity: "Mythic",
    class: "Support",
    gender: "Male",
    released: "2021",
  },
  stu: {
    rarity: "Epic",
    class: "Assassin",
    gender: "Male",
    released: "2021",
  },
  belle: {
    rarity: "Epic",
    class: "Marksman",
    gender: "Female",
    released: "2021",
  },
  squeak: {
    rarity: "Mythic",
    class: "Controller",
    gender: "Non-binary",
    released: "2021",
  },
  grom: {
    rarity: "Epic",
    class: "Artillery",
    gender: "Male",
    released: "2021",
  },
  buzz: {
    rarity: "Mythic",
    class: "Assassin",
    gender: "Male",
    released: "2021",
  },
  griff: {
    rarity: "Epic",
    class: "Controller",
    gender: "Male",
    released: "2021",
  },
  ash: {
    rarity: "Epic",
    class: "Tank",
    gender: "Male",
    released: "2021",
  },
  meg: {
    rarity: "Legendary",
    class: "Tank",
    gender: "Female",
    released: "2021",
  },
  lola: {
    rarity: "Epic",
    class: "Damage Dealer",
    gender: "Female",
    released: "2021",
  },
  fang: {
    rarity: "Mythic",
    class: "Assassin",
    gender: "Male",
    released: "2022",
  },
  eve: {
    rarity: "Mythic",
    class: "Damage Dealer",
    gender: "Female",
    released: "2022",
  },
  janet: {
    rarity: "Mythic",
    class: "Marksman",
    gender: "Female",
    released: "2022",
  },
  bonnie: {
    rarity: "Epic",
    class: "Marksman",
    gender: "Female",
    released: "2022",
  },
  otis: {
    rarity: "Mythic",
    class: "Controller",
    gender: "Male",
    released: "2022",
  },
  sam: {
    rarity: "Epic",
    class: "Assassin",
    gender: "Male",
    released: "2022",
  },
  gus: {
    rarity: "Super Rare",
    class: "Support",
    gender: "Male",
    released: "2022",
  },
  buster: {
    rarity: "Mythic",
    class: "Tank",
    gender: "Male",
    released: "2022",
  },
  chester: {
    rarity: "Legendary",
    class: "Damage Dealer",
    gender: "Male",
    released: "2022",
  },
  gray: {
    rarity: "Mythic",
    class: "Support",
    gender: "Male",
    released: "2023",
  },
  mandy: {
    rarity: "Epic",
    class: "Marksman",
    gender: "Female",
    released: "2023",
  },
  "r-t": {
    rarity: "Mythic",
    class: "Damage Dealer",
    gender: "Non-binary",
    released: "2023",
  },
  willow: {
    rarity: "Mythic",
    class: "Controller",
    gender: "Female",
    released: "2023",
  },
  maisie: {
    rarity: "Epic",
    class: "Marksman",
    gender: "Female",
    released: "2023",
  },
  hank: {
    rarity: "Epic",
    class: "Tank",
    gender: "Male",
    released: "2023",
  },
  cordelius: {
    rarity: "Legendary",
    class: "Assassin",
    gender: "Male",
    released: "2023",
  },
  doug: {
    rarity: "Mythic",
    class: "Support",
    gender: "Male",
    released: "2023",
  },
  pearl: {
    rarity: "Epic",
    class: "Damage Dealer",
    gender: "Female",
    released: "2023",
  },
  chuck: {
    rarity: "Mythic",
    class: "Controller",
    gender: "Male",
    released: "2023",
  },
  charlie: {
    rarity: "Mythic",
    class: "Controller",
    gender: "Female",
    released: "2023",
  },
  mico: {
    rarity: "Mythic",
    class: "Assassin",
    gender: "Male",
    released: "2023",
  },
  kit: {
    rarity: "Legendary",
    class: "Support",
    gender: "Male",
    released: "2024",
  },
  "larry & lawrie": {
    rarity: "Epic",
    class: "Artillery",
    gender: "Male",
    released: "2024",
  },
  melodie: {
    rarity: "Mythic",
    class: "Assassin",
    gender: "Female",
    released: "2024",
  },
  angelo: {
    rarity: "Epic",
    class: "Marksman",
    gender: "Non-binary",
    released: "2024",
  },
  draco: {
    rarity: "Legendary",
    class: "Tank",
    gender: "Male",
    released: "2024",
  },
  lily: {
    rarity: "Mythic",
    class: "Assassin",
    gender: "Female",
    released: "2024",
  },
  berry: {
    rarity: "Epic",
    class: "Support",
    gender: "Male",
    released: "2024",
  },
  clancy: {
    rarity: "Mythic",
    class: "Damage Dealer",
    gender: "Male",
    released: "2024",
  },
  moe: {
    rarity: "Mythic",
    class: "Damage Dealer",
    gender: "Male",
    released: "2024",
  },
  kenji: {
    rarity: "Legendary",
    class: "Assassin",
    gender: "Male",
    released: "2024",
  },
  shade: {
    rarity: "Epic",
    class: "Assassin",
    gender: "Non-binary",
    released: "2024",
  },
  juju: {
    rarity: "Mythic",
    class: "Artillery",
    gender: "Female",
    released: "2024",
  },
  meeple: {
    rarity: "Epic",
    class: "Controller",
    gender: "Non-binary",
    released: "2025",
  },
  ollie: {
    rarity: "Mythic",
    class: "Tank",
    gender: "Male",
    released: "2025",
  },
  finx: {
    rarity: "Mythic",
    class: "Controller",
    gender: "Male",
    released: "2025",
  },
  lumi: {
    rarity: "Mythic",
    class: "Damage Dealer",
    gender: "Female",
    released: "2025",
  },
  "jae-yong": {
    rarity: "Mythic",
    class: "Support",
    gender: "Male",
    released: "2025",
  },
  kaze: {
    rarity: "Ultra Legendary",
    class: "Assassin",
    gender: "Female",
    released: "2025",
  },
  alli: {
    rarity: "Mythic",
    class: "Assassin",
    gender: "Female",
    released: "2025",
  },
  trunk: {
    rarity: "Epic",
    class: "Tank",
    gender: "Non-binary",
    released: "2025",
  },
  mina: {
    rarity: "Mythic",
    class: "Damage Dealer",
    gender: "Female",
    released: "2025",
  },
  ziggy: {
    rarity: "Mythic",
    class: "Controller",
    gender: "Male",
    released: "2025",
  },
};

export const brawlers = Object.keys(data);